### PR TITLE
Plant CI

### PR DESCRIPTION
**Pull request by lucafavatella**
Supersedes #4.

I took the liberty of relying on Python 3 because of much easier Unicode handling.

### CODE REVIEW

**Comment by lucafavatella** [comment]
Output of e700398 with py-sblgnt 0.4 (the one in master and kept in this PR) is:
```
Lemma μήν shall be included because in py-sblgnt. Full py-sblgnt row is: {'bcv': '030124', 'ccat-pos': 'N-', 'ccat-parse': '----APM-', 'robinson': 'N-APM', 'text': 'μῆνας', 'word': 'μῆνας', 'norm': 'μῆνας', 'lemma': 'μήν'}.
Lemma μήν shall be included because in py-sblgnt. Full py-sblgnt row is: {'bcv': '030126', 'ccat-pos': 'N-', 'ccat-parse': '----DSM-', 'robinson': 'N-DSM', 'text': 'μηνὶ', 'word': 'μηνὶ', 'norm': 'μηνί', 'lemma': 'μήν'}.
Lemma μήν shall be included because in py-sblgnt. Full py-sblgnt row is: {'bcv': '030136', 'ccat-pos': 'N-', 'ccat-parse': '----NSM-', 'robinson': 'N-NSM', 'text': 'μὴν', 'word': 'μὴν', 'norm': 'μήν', 'lemma': 'μήν'}.
Lemma μήν shall be included because in py-sblgnt. Full py-sblgnt row is: {'bcv': '030156', 'ccat-pos': 'N-', 'ccat-parse': '----APM-', 'robinson': 'N-APM', 'text': 'μῆνας', 'word': 'μῆνας', 'norm': 'μῆνας', 'lemma': 'μήν'}.
Lemma μήν shall be included because in py-sblgnt. Full py-sblgnt row is: {'bcv': '030425', 'ccat-pos': 'N-', 'ccat-parse': '----APM-', 'robinson': 'N-APM', 'text': 'μῆνας', 'word': 'μῆνας', 'norm': 'μῆνας', 'lemma': 'μήν'}.
Lemma καταβιβάζω shall be included because in py-sblgnt. Full py-sblgnt row is: {'bcv': '031015', 'ccat-pos': 'V-', 'ccat-parse': '2FPI-S--', 'robinson': 'V-FPI-2S', 'text': '⸀καταβιβασθήσῃ.', 'word': 'καταβιβασθήσῃ', 'norm': 'καταβιβασθήσῃ', 'lemma': 'καταβιβάζω'}.
Lemma μήν shall be included because in py-sblgnt. Full py-sblgnt row is: {'bcv': '050720', 'ccat-pos': 'N-', 'ccat-parse': '----APM-', 'robinson': 'N-APM', 'text': 'μῆνας', 'word': 'μῆνας', 'norm': 'μῆνας', 'lemma': 'μήν'}.
Lemma μήν shall be included because in py-sblgnt. Full py-sblgnt row is: {'bcv': '051811', 'ccat-pos': 'N-', 'ccat-parse': '----APM-', 'robinson': 'N-APM', 'text': 'μῆνας', 'word': 'μῆνας', 'norm': 'μῆνας', 'lemma': 'μήν'}.
Lemma μήν shall be included because in py-sblgnt. Full py-sblgnt row is: {'bcv': '051908', 'ccat-pos': 'N-', 'ccat-parse': '----APM-', 'robinson': 'N-APM', 'text': 'μῆνας', 'word': 'μῆνας', 'norm': 'μῆνας', 'lemma': 'μήν'}.
Lemma μήν shall be included because in py-sblgnt. Full py-sblgnt row is: {'bcv': '052003', 'ccat-pos': 'N-', 'ccat-parse': '----APM-', 'robinson': 'N-APM', 'text': 'μῆνας', 'word': 'μῆνας', 'norm': 'μῆνας', 'lemma': 'μήν'}.
Lemma μήν shall be included because in py-sblgnt. Full py-sblgnt row is: {'bcv': '052811', 'ccat-pos': 'N-', 'ccat-parse': '----APM-', 'robinson': 'N-APM', 'text': 'μῆνας', 'word': 'μῆνας', 'norm': 'μῆνας', 'lemma': 'μήν'}.
Lemma μήν shall be included because in py-sblgnt. Full py-sblgnt row is: {'bcv': '090410', 'ccat-pos': 'N-', 'ccat-parse': '----APM-', 'robinson': 'N-APM', 'text': 'μῆνας', 'word': 'μῆνας', 'norm': 'μῆνας', 'lemma': 'μήν'}.
Lemma ὑπερβαίνω shall be included because in py-sblgnt. Full py-sblgnt row is: {'bcv': '130406', 'ccat-pos': 'V-', 'ccat-parse': '-PAN----', 'robinson': 'V-PAN', 'text': 'ὑπερβαίνειν', 'word': 'ὑπερβαίνειν', 'norm': 'ὑπερβαίνειν', 'lemma': 'ὑπερβαίνω'}.
Lemma μήν shall be included because in py-sblgnt. Full py-sblgnt row is: {'bcv': '190614', 'ccat-pos': 'X-', 'ccat-parse': '--------', 'robinson': 'PRT', 'text': 'μὴν', 'word': 'μὴν', 'norm': 'μήν', 'lemma': 'μήν'}.
Lemma μήν shall be included because in py-sblgnt. Full py-sblgnt row is: {'bcv': '200517', 'ccat-pos': 'N-', 'ccat-parse': '----APM-', 'robinson': 'N-APM', 'text': 'μῆνας', 'word': 'μῆνας', 'norm': 'μῆνας', 'lemma': 'μήν'}.
Lemma μήν shall be included because in py-sblgnt. Full py-sblgnt row is: {'bcv': '270905', 'ccat-pos': 'N-', 'ccat-parse': '----APM-', 'robinson': 'N-APM', 'text': 'μῆνας', 'word': 'μῆνας', 'norm': 'μῆνας', 'lemma': 'μήν'}.
Lemma μήν shall be included because in py-sblgnt. Full py-sblgnt row is: {'bcv': '270910', 'ccat-pos': 'N-', 'ccat-parse': '----APM-', 'robinson': 'N-APM', 'text': 'μῆνας', 'word': 'μῆνας', 'norm': 'μῆνας', 'lemma': 'μήν'}.
Lemma μήν shall be included because in py-sblgnt. Full py-sblgnt row is: {'bcv': '270915', 'ccat-pos': 'N-', 'ccat-parse': '----ASM-', 'robinson': 'N-ASM', 'text': 'μῆνα', 'word': 'μῆνα', 'norm': 'μῆνα', 'lemma': 'μήν'}.
Lemma μήν shall be included because in py-sblgnt. Full py-sblgnt row is: {'bcv': '271102', 'ccat-pos': 'N-', 'ccat-parse': '----APM-', 'robinson': 'N-APM', 'text': 'μῆνας', 'word': 'μῆνας', 'norm': 'μῆνας', 'lemma': 'μήν'}.
Lemma μήν shall be included because in py-sblgnt. Full py-sblgnt row is: {'bcv': '271305', 'ccat-pos': 'N-', 'ccat-parse': '----APM-', 'robinson': 'N-APM', 'text': 'μῆνας', 'word': 'μῆνας', 'norm': 'μῆνας', 'lemma': 'μήν'}.
Lemma μήν shall be included because in py-sblgnt. Full py-sblgnt row is: {'bcv': '272202', 'ccat-pos': 'N-', 'ccat-parse': '----ASM-', 'robinson': 'N-ASM', 'text': 'μῆνα', 'word': 'μῆνα', 'norm': 'μῆνα', 'lemma': 'μήν'}.
Lexeme μήν/N shall not be included because not among py-sblgnt lemmas. Full lexeme metadata is: {'pos': 'N', 'full-citation-form': 'μήν, ηνός, ὁ', 'bdag-headword': 'μήν', 'danker-entry': 'μήν, μηνός, ὁ', 'dodson-entry': 'μήν, μηνός, ὁ', 'mounce-headword': 'μήν', 'strongs': 3376, 'gk': 3604, 'dodson-pos': 'N:M', 'gloss': 'a month', 'mounce-morphcat': 'n-3f(1a)'}.
Lexeme μήν/X shall not be included because not among py-sblgnt lemmas. Full lexeme metadata is: {'pos': 'X', 'bdag-headword': 'μήν', 'danker-entry': 'μήν', 'dodson-entry': 'μήν', 'mounce-headword': 'μήν', 'strongs': 3375, 'gk': 3605, 'dodson-pos': 'PRT', 'gloss': 'certainly', 'mounce-morphcat': 'particle'}.
Lexeme Νυμφᾶς shall not be included because not among py-sblgnt lemmas. Full lexeme metadata is: {'pos': 'N', 'full-citation-form': 'Νυμφᾶς, ᾶ, ὁ', 'bdag-headword': 'Νυμφᾶς', 'danker-entry': 'Νυμφᾶς, ᾶ, ὁ', 'dodson-entry': 'Νυμφᾶς, ᾶ, ὁ', 'strongs': 3564, 'gk': 3810, 'dodson-pos': 'N:M', 'gloss': 'Nymphas', 'mounce-morphcat': 'n-1e'}.
Checking that word set in /Users/luca/dev/morphological-lexicon/missing_bdag.txt is Unicode normalized...
Checking that word set in /Users/luca/dev/morphological-lexicon/missing_danker.txt is Unicode normalized...
Checking that word set in /Users/luca/dev/morphological-lexicon/missing_dodson.txt is Unicode normalized...
Checking that word set in /Users/luca/dev/morphological-lexicon/missing_morphcat.txt is Unicode normalized...
Checking that word set in /Users/luca/dev/morphological-lexicon/missing_mounce.txt is Unicode normalized...
```

Output of e700398 with py-sblgnt 0.5 (bumped locally, not committed) has the following differences from 0.4:
```
> Lexeme ἄγε shall not be included because not among py-sblgnt lemmas. Full lexeme metadata is: {'pos': 'V', 'bdag-headword': 'ἄγε', 'danker-entry': 'ἄγε'}.
> Lexeme δεῖ shall not be included because not among py-sblgnt lemmas. Full lexeme metadata is: {'pos': 'V', 'bdag-headword': 'δεῖ', 'danker-entry': 'δεῖ', 'dodson-entry': 'δεῖ', 'mounce-headword': 'δεῖ', 'strongs': 1163, 'gk': 1256, 'dodson-pos': 'V', 'gloss': 'it is necessary, inevitable', 'mounce-morphcat': 'v-1d(2c)'}.
> Lexeme ἱερόν shall not be included because not among py-sblgnt lemmas. Full lexeme metadata is: {'pos': 'A/N', 'full-citation-form': 'ἱερόν, οῦ, τό', 'bdag-headword': 'ἱερόν', 'danker-entry': 'ἱερόν, οῦ, τό', 'dodson-entry': 'ἱερόν, οῦ, τό', 'mounce-headword': 'ἱερόν', 'strongs': 2411, 'gk': 2639, 'dodson-pos': 'N:N', 'gloss': 'a temple', 'mounce-morphcat': 'n-2c'}.
> Lexeme σύνιημι shall not be included because not among py-sblgnt lemmas. Full lexeme metadata is: {'pos': 'V', 'bdag-headword': 'συνίημι', 'danker-entry': 'συνίημι/συνίω', 'dodson-entry': 'συνίημι', 'mounce-headword': 'συνίημι', 'strongs': 4920, 'gk': 5317, 'dodson-pos': 'V', 'gloss': 'I consider, understand', 'mounce-morphcat': 'cv-6a'}.
```

**Comment by lucafavatella** [comment]
(off topic) @jtauber BTW I have a work-in-progress branch where I attempt to make the add_dodson.py script run reproducibly from [online copy of Dodson](https://raw.githubusercontent.com/biblicalhumanities/Dodson-Greek-Lexicon/5f140b84bd7541cd883acf9b1e0e43e383d677e6/dodson.csv). Such copy of (machine-parseable) Dodson lacks pos - please let me know if you suggest other reference. (My end goal is reviewing the Strong numbers in lexemes.yaml as I got the impression that some are wrong.)

**Comment by jtauber** [comment]
I'm fine with assuming Python 3 for all this work.

**Comment by jtauber** [comment]
Regarding Strongs being wrong: it's sometimes hard to know what it means for Strongs numbers to be wrong given how people use them (see my 2006 paper <https://www.academia.edu/19660777/A_New_Numbering_System_for_Greek_New_Testament_Lexemes_2006_>). The only reason I include them in this file is to help with integrating other resources that use them. Otherwise I would avoid them :-)

**Comment by lucafavatella** [comment]
Additional output at 09c94e1 (still py-sblgnt 0.4):
```
Checking that word set in /Users/luca/dev/morphological-lexicon/missing_bdag.txt contains only lexemes from the lexemes file /Users/luca/dev/morphological-lexicon/lexemes.yaml...
Word φαρμακός shall be removed from the set because not among lexemes in lexemes file.
Word στοιχεῖα shall be removed from the set because not among lexemes in lexemes file.
Word Ἐλαιῶν shall be removed from the set because not among lexemes in lexemes file.
Checking that word set in /Users/luca/dev/morphological-lexicon/missing_danker.txt contains only lexemes from the lexemes file /Users/luca/dev/morphological-lexicon/lexemes.yaml...
Word φαρμακός shall be removed from the set because not among lexemes in lexemes file.
Word στοιχεῖα shall be removed from the set because not among lexemes in lexemes file.
Checking that word set in /Users/luca/dev/morphological-lexicon/missing_dodson.txt contains only lexemes from the lexemes file /Users/luca/dev/morphological-lexicon/lexemes.yaml...
Word πραϋπάθια shall be removed from the set because not among lexemes in lexemes file.
Word φαρμακός shall be removed from the set because not among lexemes in lexemes file.
Word στοιχεῖα shall be removed from the set because not among lexemes in lexemes file.
Checking that word set in /Users/luca/dev/morphological-lexicon/missing_morphcat.txt contains only lexemes from the lexemes file /Users/luca/dev/morphological-lexicon/lexemes.yaml...
Word φαρμακός shall be removed from the set because not among lexemes in lexemes file.
Word μήν shall be removed from the set because not among lexemes in lexemes file.
Word Νύμφας shall be removed from the set because not among lexemes in lexemes file.
Word στοιχεῖα shall be removed from the set because not among lexemes in lexemes file.
Checking that word set in /Users/luca/dev/morphological-lexicon/missing_mounce.txt contains only lexemes from the lexemes file /Users/luca/dev/morphological-lexicon/lexemes.yaml...
Word Νύμφας shall be removed from the set because not among lexemes in lexemes file.
Word στοιχεῖα shall be removed from the set because not among lexemes in lexemes file.
Word φαρμακός shall be removed from the set because not among lexemes in lexemes file.
```

**Comment by jtauber** [comment]
@lucafavatella it might be helpful for you to join http://bibletechnology-slack.herokuapp.com so we can chat about all this stuff more easily.

**Pull request merged**
